[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = "0.9.8"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
spin = "0.10.0"

[lib]
name = "libnedo"
path = "src/libnedo/lib.rs"

[[bin]]
name = "kernel"
path = "src/main.rs"

