[package]
name = "nedo_os_2"
version = "0.1.0"
edition = "2024"

[lib]
name = "libnedo"
path = "src/libnedo/lib.rs"

[[bin]]
name = "nedo_os_2"
path = "src/main.rs"

[dependencies]
lazy_static = { version = "1.5.0", features = ["spin_no_std"]}
spin = "0.10.0"

